### ISSUE TITLE
Maximizing two parameters are not working.

### ISSUE THREAD

**Issue by efeint01** [kernc/backtesting.py#1012]
I simply made this function and trades condition not working. **My goal is maximize Trades and Avg. Trade**

```
def optim_func(series):
    if series['# Trades'] < 50:
        return -1
    else:
        return series['Avg. Trade [%]']

```

Then i ran like this:

```
    bt = Backtest(df, StokRsı, cash=100_000, commission=.0004)
    stats = bt.optimize(
        maximize=optim_func,
        # method="grid",
        max_tries=50
    )

```

I wanna at least 50 trades. But it's gave me 10 trades.

**Comment by kernc** [comment]
> I wanna at least 50 trades. But it's gave me 10 trades.

Simply, `-1` is the greatest number your `optim_func()` ever returns!

[`Backtest.optimize(max_tries=)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.optimize) constrains the number of optimization runs. Since you don't seem to have any flexible parameters to optimize for (strategy class variables; values passed as `**kwargs` to `Backtest.optimize()`), 10 trades is all you're ever gonna get ...

**Comment by efeint01** [comment]
Thanks
