### ISSUE TITLE
Example Strategy for MACD using TA

### ISSUE THREAD

**Issue by scottstables** [kernc/backtesting.py#15]
Hi - I 'm trying to understand how to use indicators from the TA library (e.g. https://pypi.org/project/ta/) within a strategy ?

Has anyone created an example they can share ?

thank you

**Comment by kernc** [comment]
Indicators are evaluated lazily by the [`Strategy.I()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.I) function. This means you don't call the indicator function yourself (e.g. `ta.macd(...)`), but you let `Strategy.I()` call the function and the supplied parameters sometime later (e.g. `self.I(ta.macd, ...)`). For example:
```py
import pandas as pd
import ta
from backtesting import Strategy

class MyStrategy(Strategy):
    def init(self):
        macd_values = self.I(ta.macd, pd.Series(self.data.Close), 12, 26)
    ...
```
Note, price values supplied to `ta` indicators need to be pandas series objects because the former indicator library is apparently not particularly robust in handling other array-like structures.

Welcome to go over [tutorials](https://kernc.github.io/backtesting.py/doc/backtesting/#manuals) for more usage examples.

**Comment by chhudson** [comment]
@kernc - Thank you for this. Adding `pd.Series(...)` dramatically improved the overall performance of a strategy I've been working on!!!

Just to confirm:
```
def init(self):
        self.scci = self.I(ta.CCI, pd.Series(self.data.High),pd.Series(self.data.Low),pd.Series(self.data.Close), self.cci_tp)
        self.sadr = self.I(ta.ATR, pd.Series(self.data.High),pd.Series(self.data.Low), pd.Series(self.data.Close), self.adr_tp)
```

**Comment by kernc** [comment]
> Adding pd.Series(...) dramatically improved the overall performance

Maybe with `ta` library. In general, that absolutely positively shouldn't be the case. Pandas is a fast and tremendously _convenient_ and user-friendly library to work with, but compared to raw numpy, it's not that fast (in most places, anyway).

**Comment by Rishabh-1911** [comment]
I am having trouble in using bt.optimize for macd indicator. How do we define the variables in class which will be passed parameters from bt.optimize()

**Comment by sumobull** [comment]
Do you have a quick functional example getting this to work with tulipy?  I can't seem to get the data structure correct when passing to self.I().

**Comment by kernc** [comment]
@Rishabh-1911, @sumobull Simply
```py
self.I(ti.macd, self.data.Close, 2, 5, 9)
```
would work if it were not for bug https://github.com/cirla/tulipy/issues/30 (if you care enough, please upvote / raise your voice in that issue, or even maybe open a new issue — the community interest needs to be shown). The problem is that tulipy indicators return a shorter array, stripped of leading NaNs, so Backtesting complains since the result array is not of the expected size. I'm afraid for the time being, as the issue recommends, you'll have to pad the result arrays yourselves:
```py
def tulip_pad(func, *args, **kwargs):
    result = func(*args, **kwargs)
    size = len(args[0])
    padded = np.r_[[np.nan]*(size - x.size), x]
    return padded

self.I(tulip_pad, ti.macd, self.data.Close, 2, 5, 9)
```

**Comment by kiann00** [comment]
Hi @kernc , thanks... your backtesting.py is really lightweight and powerful. ...

just want to confirm the syntax structure if we use the python module 'ta', instead of pandas_ta
specifically, for MACD, if we pump just pump in the data time-series : self.data.Close.to_series(), it works with the macd_diff signal?

For example, the TA specifics macd_diff = macd_trend - macd_signal = func[sma(12), sma(26), sma(9)]
so, if I use the below, will it work as intended? I ran it, and I didnt see any programming errors, but I am not sure if the *** results *** generated are correct.

```
class Signal_Strategy_v1(Strategy):
    # lets do a sweep of multiple technical indicators and try to do backtesting optimization using backtesting.py
    
    macd_fast = 12
    macd_slow = 26
    macd_sig = 9
    macd_upper = +2.5
    macd_lower = -2.5
    # Do as much initial computation as possible
    def init(self):
        self.rsi = self.I(ta_.momentum.rsi, pd.Series(self.data.Close), self.rsi_window)
        self.macd = self.I(ta_.trend.macd_diff, self.data.Close.to_series(), \
                  self.macd_fast, self.macd_slow, self.macd_sig)

```
