### ISSUE TITLE
Expectancy [%] formula

### ISSUE THREAD

**Issue by paklong** [kernc/backtesting.py#180]
Hi, I really love your project, it really helps me a lot!

I found that the current expectancy formula is:

https://github.com/kernc/backtesting.py/blob/17e948903ac9adf5b9d096f1807ac6db9c099e63/backtesting/backtesting.py#L1444-L1445
But it seems that the correct formula should be:
```
s.loc['Expectancy [%]'] = ((returns[returns > 0].mean() * win_rate + 
                            returns[returns < 0].mean() * (100 - win_rate)))
```
Because the Expectancy = ΣX * P(X)

Thanks again for your great work!

**Comment by kernc** [comment]
... and `returns[returns < 0].mean()` is already negative. Yikes!

Care to make a pull request with the change?

**Comment by sbushmanov** [comment]
First of all thanks for this fascinating project!

Why not simplify

`returns[returns > 0].mean() * win_rate - returns[returns < 0].mean() * (100 - win_rate))`

to just:

`returns.means()*100`

E.g.:

```
np.random.seed(42)
returns = np.random.randn(10)
returns.mean()*100
#44.80611116987562
```
and:
```
win_rate = (returns>0).sum()/len(returns)*100
returns[returns>0].mean()*win_rate + returns[returns<0].mean()*(100-win_rate)
#44.80611116987563
```
As well, averaging over trades with different durations may be misleading. More meaningful would be to provide say a per day geometric average return expectancy.

**Comment by kernc** [comment]
@sbushmanov Apparently, we didn't know better. :sweat_smile: I admit to not seeing it, so I trust the equivalence holds also in symbolic form.

> per day geometric average return expectancy

Would you care to make a PR with that change?

**Comment by sbushmanov** [comment]
I have a feeling if we try to calculate `Expectancy` as daily/annual returns -- which was my initial idea -- we should end up with the figure you already have, i.e. `Return (Ann.) [%]`. Afterall, realized annual return is what you should expect to happen in the future.

I suspect I understand the concept of Expectancy as defined [here](https://vantagepointtrading.com/what-is-trading-expectancy-and-how-it-works/) and [here](https://www.axi.com/uk/blog/education/expectancy-forex#:~:text=What%20is%20expectancy%3F,be%201.2%20times%20your%20risk.), but I don't like it as average gain per trade can be gamed: expectancy of $100 on $1'000'000 seems preferable to  $99 on $1'000.

So I suggest either you (1) leave it as you have as a mean return per trade or (2) calculate absolute amount of gain per trade as they define or (3) leave it out altogether.

**Comment by kernc** [comment]
> expectancy of $100 on $1'000'000 seems preferable to $99 on $1'000.

That's why we use relative returns:
https://github.com/kernc/backtesting.py/blob/bbcb7bac8ffe65a5002edfcdf8bc50f92eaca2b9/backtesting/backtesting.py#L1527

> (Win % x Average Win Size) – (Loss % x Average Loss Size)

> (total R) / (number of trades) = expectancy

This (equations from the two links) looks exactly like what we are doing now.

**Comment by sbushmanov** [comment]
My point was averageing say 1% for a one day trade and 1% for a trade lasting 1 year is misleading...  

It's not as misleading as averaging absolute amounts but still. Even annualizing this measure will leave people wondering why there is a difference between annualized returns and annualized expectancy and which one I should rely on.

**Comment by eervin123** [comment]
@sbushmanov I see your point, but I just think of it as a slightly different dimension on the data.  This is very subtle so indulge me a little, the annualized returns are a high level 50,000 foot view of the strategy itself. The expectancy % is a different look at how the strategy was able to achieve those annualized returns.  The entire stats table is merely a quick glance at a number of dimensions of the same data. If you glance at the number of trades coupled with the win rate, and the expectancy % you can start to get a better perspective on how those overall returns might have been generated so you can better identify other sample periods where you can try to break the backtest and shock the strategy to see how those numbers change.   I think we would all agree that these are just backtests after all, so the results are only a guide.  Personally, I don't really have a strong opinion one way or another on this singular issue, I just wanted to chime in so you had a different point of view. Keep in mind though that this is more of a general purpose framework so I personally wouldn't recommend annualizing it because as you point out, the annualized number is already present above. If someone were working on a single day with 1 second intervals, the expectancy % in it's current form would be far more meaningful, and vice versa, perhaps if they had a slow moving strategy that made fairly few trades over a 50 year horizon, the expectancy % might be much less meaningful than the annualized % returns.

Regarding your point about evaluating different holding period returns based on different trades,
> My point was averaging say 1% for a one day trade and 1% for a trade lasting 1 year is misleading...

It would be misleading if that was all we were given, but we have the entire stats table to better understand at a glance what is going on so I don't think this is as challenging as it may seem.  And I know this wasn't your point, but, from a investor's perspective, all of the trades are relevant, the ones that last a day or the ones that last a year. The decision not to sell or buy every day for a year may not be a trade on the trading blotter, but it is a decision nonetheless.  This is why I am more partial to looking at beefing up the rolling period returns and creating simple "relative return" metrics to better disect where alpha may be coming from ie. timing luck, short attribution, long attribution, trade quantity, size, etc. etc. As an example, the `relative expectancy %` where 
Win% would be calculated as the excess % return over the benchmark [(TradePNL-benchmarkPNL) > 0] and vice versa for loss % in your calculation below.
>(Win % x Average Win Size) – (Loss % x Average Loss Size)

The idea would be to also calculate the periods the strategy was in cash relative to the benchmark as "relative" wins or losses as well.

For the record, "benchmark" could be anything, but I think the default would be buy and hold.
