### ISSUE TITLE
Dividend and Splits

### ISSUE THREAD

**Issue by adamsau** [kernc/backtesting.py#185]
Any standard way to handle dividend and splits like adjusting equities shares/orders?

**Comment by adamsau** [comment]
or should I use adjusted OHLC?

**Comment by kernc** [comment]
> or should I use adjusted OHLC?

That would be the easiest, seamless, and technically valid approach.

**Comment by Buddyli82** [comment]
Following up on this question... Does adjusted Open when Dividend is issued affect the return of an open position? For example, consider the following scenario:
1) Day 1: Enter a position with buy price is $10.
2) Day 2: Dividend amount is $0.01 is declared (ex-date).  Stock price still at $10.0.  Current Profit = $10.0 - $10.0 = $0.0
3) Day 3: The open price is $9.99 to reflect dividend issued, then on however, the profit should reflect: Current Profit = $9.99 - $10.0 + $0.01 = $0.0.  Instead of Current Profit = $9.99 - $10.0 = - $0.01 (loss).
4) Day 4: Stock price goes up to $10.20 and we decide to close position.  Total Profit (actual) = $10.20 - $10.00 + $0.01 = $0.21.

Is there a way to implement that into Return based on dividend ex-dates and dividend amounts?

**Comment by pringithub** [comment]
^ bump
