### ISSUE TITLE
Order type

### ISSUE THREAD

**Issue by s-kust** [kernc/backtesting.py#190]
How to implement the instruction "close the position today on market close", i.e. Market-On-Close (MOC) Order?
Also, how to implement "enter the trade tomorrow on market open"?

**Comment by kernc** [comment]
What is the frequency of your OHLC data?

All orders are made Good-Til-Canceled, so you have to implement `if time_to_close` logic yourself.

**Comment by s-kust** [comment]
> you have to implement if time_to_close logic yourself.

Can you please tell me how to extract Date and Time from the data index separately? And how to compare time?

Let's saay I have 5-minutes candles data. How to implement "if time is 18:55:00, close position"?

**Comment by kernc** [comment]
As mentioned in https://github.com/kernc/backtesting.py/issues/188, index values are [`pandas.Timestamp`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html). So, in order to get time only, you'd call their `.time()` method, or their `.hour`/`.minute` attributes.

General programming questions like these currently fit best on [StackOverflow](https://stackoverflow.com/) or similar.
