### ISSUE TITLE
Pre-computed indicator values results in look-ahead bias

### ISSUE THREAD

**Issue by crazy25000** [kernc/backtesting.py#277]
Read through the documentation and tutorials, when I first read that all indicator values were computed in `__init__`, this stayed in the back of my mind. 

By computing the indicator values using all the OHLC data, instead of the data it should have access to for that day/time, this creates a look-ahead bias. Looking at the indicator method  `def I` : https://github.com/kernc/backtesting.py/blob/73e1534428fc2db9e681030862133b5067508520/backtesting/backtesting.py#L124-L134

Is this expected/by design?

**Comment by kernc** [comment]
>  all indicator values were computed in `__init__`

It's [_`init()`_, `Strategy.init()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.init), called separately from the [constructor](https://github.com/kernc/backtesting.py/blob/73e1534428fc2db9e681030862133b5067508520/backtesting/backtesting.py#L50-L54).



> using all the OHLC data ... this creates a look-ahead bias

If you pass data to a function that has a look-ahead bias, then yes, it's by design you're able to shoot yourself in the foot. Here's an example of a few functions that don't have a look-ahead bias:
* `lambda x: pd.Series(x).rolling(20).mean()`
* `talib.SMA(x, 20)`
* `tulipy.sma(x, 20)`

And an example of a function that _does have it_:
* `lambda x: pd.Series(x).rolling(20, center=True).mean()`

So, indeed, you have to be mindful of what you're doing.

Alternatively, you're free to compute (continually recompute) your indicators in [`next()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.next).

**Comment by crazy25000** [comment]
I've been using talib, I didn't know `talib.SMA(x, 20)` wouldn't have look ahead bias. This was the case I worried about and recomputing was going to be the backup plan if look ahead bias was happening with talib indicators. Thanks for the clarification, going to close this.

**Comment by crazy25000** [comment]
I ran a simple cross over strategy using 2 talib EMA, a SL, and a TP, but used 2 different methods for computing indicator values. The results were identical, but computation time was not. Posting here for future reference:

1. Using computed indicator values
```
CPU times: user 1.27 s, sys: 0 ns, total: 1.27 s
Start               2020-01-01 22:00:00+00:00
End                 2020-12-31 21:55:00+00:00
Duration                    364 days 23:55:00
Equity Final [$]                    988.41093
Return [%]                          -1.158907
Profit Factor                        0.973236
SQN                                 -0.372168
Trades won                                386
Trades lost                               351
Trades total                              737
```

2. Continually computing indicator values in the `next` method
```
CPU times: user 12.2 s, sys: 0 ns, total: 12.2 s
Start               2020-01-01 22:00:00+00:00
End                 2020-12-31 21:55:00+00:00
Duration                    364 days 23:55:00
Equity Final [$]                    988.41093
Return [%]                          -1.158907
Profit Factor                        0.973236
SQN                                 -0.372168
Trades won                                386
Trades lost                               351
Trades total                              737
```
