### ISSUE TITLE
Plotted data and printed stats don't match

### ISSUE THREAD

**Issue by Pilipets** [kernc/backtesting.py#362]
**Max drawdown duration** is 273 days from the plot, but 248 days from the stats.

![2](https://user-images.githubusercontent.com/22419519/119558942-b5602880-bdaa-11eb-91b1-2ca8bd5730fc.png)
![3](https://user-images.githubusercontent.com/22419519/119559129-f0625c00-bdaa-11eb-8648-71556cdf0c7d.png)

**Comment by kernc** [comment]
The issue is not observed in the simple [examples that accompany the distribution](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html).

Are you, perchance, using more than:
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/_plotting.py#L92
bars of input data, with some downsampling ([`bt.plot(resample=)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.plot)) taking place?

There are indeed two different code paths: stats:
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/backtesting.py#L1594
using:
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/backtesting.py#L1493-L1513
And plot:
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/_plotting.py#L285-L294
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/_plotting.py#L362-L367

I'd consider `stats` value the more reliable one.

Appreciate any further investigation you can do.

**Comment by Pilipets** [comment]
Here is the version `Backtesting==0.3.1`

**Comment by kernc** [comment]
It's most likely that the issue is a rounding error that stems from plot resampling ([`Backtest.plot(resample=)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.plot)). Plotting resamples very early in its pipeline:
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/_plotting.py#L186-L189

**Comment by Pilipets** [comment]
> It's most likely that the issue is a rounding error that stems from plot resampling ([`Backtest.plot(resample=)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.plot)). Plotting resamples very early in its pipeline:
> https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/_plotting.py#L186-L189

```
backtest = Backtest(df, *, cash=*.cash, commission=.002, hedging=True)
print(backtest.run())
backtest.plot(resample=True, filename="temp2.html")
```

I'm using resampling as above.

**Comment by Pilipets** [comment]
What I can't understand, is how the duration can be 698 if the start date is 2020-01-07 and the end date is 2021-12-06?

**Comment by Pilipets** [comment]
But why trades amount is different as well - 68 vs 175?
![image](https://user-images.githubusercontent.com/22419519/119738717-cb90e600-be89-11eb-85fd-ab5e63b881a5.png)
![image](https://user-images.githubusercontent.com/22419519/119738761-e06d7980-be89-11eb-911c-db61ccacf210.png)

**Comment by kernc** [comment]
I'm fairly confident it's due to brefore-plot resampling. See how trades are resampled and weighted aggregated on the bottom here:
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/_plotting.py#L92-L146

Plot trade count is then inferred simply as length of the data frame:
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/_plotting.py#L478-L481

Improvements are always welcome! :grin: 

If you avoid resampling by running:
```py
backtest.plot(resample=False, filename="temp2.html")
```
or:
```py
backtest.plot(resample=1_000_000, filename="temp2.html")  # Some large number
```
you should see values more aligned with those expected.
