### ISSUE TITLE
Add plot_heatmaps legend

### ISSUE THREAD

**Issue by arisliang** [kernc/backtesting.py#376]
### Expected Behavior
In the [heatmap example](https://kernc.github.io/backtesting.py/doc/examples/Parameter%20Heatmap%20&%20Optimization.html), we have plot_heatmaps function which is quite nice. However it doesn't have a legend. Can we add a legend to it?

### Additional info

- Backtesting version: 0.3.1

**Comment by kernc** [comment]
At the time, I recall there were issues with attaching [colorbars](http://docs.bokeh.org/en/latest/docs/user_guide/annotations.html#color-bars) to [Bokeh grid plots](https://docs.bokeh.org/en/latest/docs/user_guide/layout.html#grid-layout-for-plots).
https://github.com/kernc/backtesting.py/blob/0a76e9655f702331c4cc2a035d040d50111ce78d/backtesting/_plotting.py#L666-L712
Maybe that has changed since. Patch welcome.

**Comment by arisliang** [comment]
I see, fine to close for now then. Can take a look in future.

**Comment by devon-n** [comment]
This would be an absolute lovely feature if its possible to revisit it
