### ISSUE TITLE
BrokenProcessPool when doing backtest.optimize

### ISSUE THREAD

**Issue by sacharbit** [kernc/backtesting.py#5]
### Expected Behavior
Returning the stats on the best run for backtest.run()

### Actual Behavior
raised a BrokenProcessPool error : A process in the process pool was terminated abruptly while the future was running or pending.

### Steps to Reproduce
bt = Backtest(df, Strat,, cash=starting_money, commission=.002)
bt.run()
stats = bt.optimize(tresholdVol=range(5,100, 5), maximize='Equity Final [$]')

### Additional info

- Backtesting version:

**Comment by kernc** [comment]
Is it possible your strategy raises an unhandled exception somewhere? Did you maybe run out of RAM? Can you attach a whole reproducible [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) example here?

**Comment by sacharbit** [comment]
```
def var(values) :
    return (pd.Series(values) - pd.Series(values).shift(1)) / pd.Series(values).shift(1)

def vol(high, low, close) :
    return (pd.Series(high) - pd.Series(low)) / pd.Series(close)

def ma(values, n):
    return pd.Series(values).rolling(n).mean()

class MyStrat(Strategy) :
    n_small = 20
    n_big = 9
    thresholdVol = 50
    
    def init(self) :
        self.volumeVar = self.I(var, self.data.Volume)
        self.priceVar = self.I(var, self.data.Close)
        self.ma_small = self.I(ma, self.data.Close, self.n_small)
        self.ma_big = self.I(ma, self.data.Close, self.n_big)
        
    def next(self) :
        if self.priceVar[-1] > 0 and self.ma_small[-1] < self.ma_big[-1] :
            self.buy()
        elif self.priceVar[-1] < 0 and self.ma_small[-1] > self.ma_big[-1] :
            self.sell()
                
#%%
                
def backtest(name) :
    df = pd.read_csv("stock_data/{}.csv".format(name))
    df["t"] = pd.to_datetime(df["t"])
    df = df.set_index("t")
    df = df[df.Volume != 0]
    bt = Backtest(df, MyStrat, cash=starting_money, commission=.002)
    return bt

#%%
bt = backtest("Apple")
#result = bt.run()
stats = bt.optimize(thresholdVol=range(5,7), maximize='Equity Final [$]')

```

It's definitely not an issue with the RAM since it's a pretty small dataset and not that many combinaisons that I ask.

**Comment by kernc** [comment]
Does it work if your wrap `bt.optimize()` call into `if __name__ == '__main__':` block?

**Comment by sacharbit** [comment]
No it doesn't. I run this on Spyder so it's already on main anyway. Does the script that I posted works for you?

**Comment by kernc** [comment]
It does, but I'm on GNU/Linux. I assumed the problem is [_spawn_ process execution method](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) on Windows which, without the main guard, may recurse (a [common multiprocessing/futures problem](https://stackoverflow.com/questions/15900366/all-example-concurrent-futures-code-is-failing-with-brokenprocesspool)).

What about if you change in backtesting code the line:
https://github.com/kernc/backtesting.py/blob/a7d1d4f3fa658290182dfa2fdbf69bffe6a8f018/backtesting/backtesting.py#L807
to use `concurrent.futures.ThreadPoolExecutor` instead of `ProcessPoolExecutor`?

**Comment by sacharbit** [comment]
it says : name 'concurrent' is not defined

**Comment by kernc** [comment]
```py
from concurrent.futures import ThreadPoolExecutor  # like ProcessPoolExecutor is

# or

import concurrent.futures
```
Thanks!

**Comment by sacharbit** [comment]
Oh Yeah! It works! Awesome!

Thank you very much for the VERY quick response.

**Comment by kernc** [comment]
This does not make the issue fixed. :smile:

Note to self: Apparently, we should opt for `ThreadPoolExecutor` (with a performance degradation warning) on platforms where `ProcessPoolExecutor` fails.

Thanks for investigating this!

**Comment by kernc** [comment]
@sacharbit Are you maybe willing to test if the workaround proposed in https://github.com/kernc/backtesting.py/pull/6 works? :sweat_smile:

**Comment by kernc** [comment]
I've been trying to reproduce this without much success. What version of Windows and Spyder were you running this on?

-----
Note to self: Switching to `ThreadPoolExecutor` won't really do with unguarded contexts. It'll just run the computation multiple times.

**Comment by sacharbit** [comment]
I was using Python 3.7 and windows 10. The spyder version is pretty irrelevant I think.

I'm sorry I didn't reply earlier, I'll try to test it this weekend, I have a lot of work right now.

**Comment by kernc** [comment]
Np. I was testing with the following piece of code:
```py
from backtesting import Backtest
from backtesting.test._test import SmaCross, GOOG

bt = Backtest(GOOG.iloc[:100], SmaCross)
res = bt.optimize(fast=[2, 3], slow=[4, 5])
```
Spyder 3.3.4, Python 3.7.3 (non-Anaconda), Windows 10.

It doesn't raise `BrokenProcessPool` exception; in Spyder, it just hangs.

Run from the command line, it raises the expected:
```text
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
This can afaik only be avoided by using a `if __name__ == '__main__'` guard, or computing without any multiprocessing support.

**Comment by kernc** [comment]
@sacharbit I've prepared a workaround in PR #6. If you want to test it in your setup, you can most likely install it with:
```bash
pip install https://github.com/kernc/backtesting.py/archive/test_5_mp_windos.zip
```
Hopefully the performance degradation is not severe (or maybe even noticeable). Looking forward to your results!

**Comment by kkanagal** [comment]
Hey everyone, running 10.15.7 Mac OS Catalina. Was running into issue above, but when I change backtesting.py (version 0.3.1) code to use ThreadPool instead, I get the following error:

~/anaconda3/lib/python3.7/site-packages/backtesting/backtesting.py in _optimize_grid()
   1350                 # Otherwise (i.e. on Windos), sequential computation will be "faster".
   1351                 if mp.get_start_method(allow_none=False) == 'fork':
-> 1352                     with concurrent.futures.ThreadPoolExecutor as executor:
   1353                         futures = [executor.submit(Backtest._mp_task, backtest_uuid, i)
   1354                                    for i in range(len(param_batches))]

AttributeError: __enter__

not sure if what's up here, any ideas?

**Comment by kkanagal** [comment]
When I switch back to ProcessPoolExecutor() I get the same issue:

-> 1352                     with ProcessPoolExecutor() as executor:
   1353                         futures = [executor.submit(Backtest._mp_task, backtest_uuid, i)
   1354                                    for i in range(len(param_batches))]

AttributeError: __enter__

**Comment by kernc** [comment]
Dont know what `AttributeError: __enter__` is about; both [Executors _are_ context managers](https://github.com/python/cpython/blob/95e4431804587a0c9d464bb7b3d5f3057bbeaccd/Lib/concurrent/futures/_base.py#L632-L637).

If you're getting `BrokenProcessPool`, since the code had been changed, feel free to open a new issue.
