### ISSUE TITLE
Algorithm slow for one minute bars

### ISSUE THREAD

**Issue by MislavSag** [kernc/backtesting.py#66]
### Expected Behavior
Execute code in reasonable time.

### Actual Behavior
Execution is slow. Execution + plotting lasts for more than 30minutes.

### Steps to Reproduce
bt.run()
bt.plot()

### Additional info
I use minute bars in my backtesting algorithm. When I call bt.run and bt.plot(), it takes a really long time to generate output sheet and plots. Is this expected behavior?

**Comment by kernc** [comment]
Mere duration of bars shouldn't play a role, rather the count is important. How many bars total?

**Comment by MislavSag** [comment]
The code is still executing, can't check it right now but from 2016-07-08 08:30:00 to  2020-04-23 20:52:00, cca million bars. I can send ou the exact number in few minutes. I have a large number of columns too. Around 320 features for my ML model.

**Comment by kernc** [comment]
I'm afraid that won't work for you. I don't know your exact strategy parameters, but you are better advised to explore/test/optimize on a sample of a few hundred executed trades, and only validate the final results on the full data set.

**Comment by MislavSag** [comment]
Yeah, I am afraid it won't work. Actually, the code never stops executing. I have no luck with becktesting frameworks. all are suitable for simple strategies like crossovers etc, but if you need to incorporate ml model there are various problems.

**Comment by uberdeveloper** [comment]
@MislavSag You could better try [vectorbt](https://github.com/polakowo/vectorbt) to experiment with features and parameters and then could run the simulation with this framework. 

If you strictly follow ML methods, then use [pycaret](https://pycaret.org/) for experimentation.

**Comment by kernc** [comment]
If one finds the algorithm slow, I'd generally recommend methods described in the [machine learning example](https://kernc.github.io/backtesting.py/doc/examples/Trading%20with%20Machine%20Learning.html) (namely: train-test split and _batch_ walk-forward optimization). In addition, there are model-based optimization and randomized grid search (#154) soon to be released.

As for plotting, since [`bt.plot(resample=)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.plot) parameter was introduced, plotting should be fast or, by default, at least contained.

Further performance improvements obviously always welcome!
