### ISSUE TITLE
Setting position size to 10% for each trade

### ISSUE THREAD

**Issue by buckydroid** [kernc/backtesting.py#709]
I want to trade with 10% of my total capital for each orders...

Can't find any information about it in the documentation.

So is there any way to do that while backtesting?

**Comment by kernc** [comment]
> Can't find any information about it in the documentation.

That's peculiar, since it's literally [mentioned everywhere](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.buy) that you can use [order `size=` between 0 and 1](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Order.size) to mean a fraction of equity:
```py
self.buy(size=0.1)  # =10%
```
