### ISSUE TITLE
A sell order always gives a loss

### ISSUE THREAD

**Issue by leowhynot** [kernc/backtesting.py#778]
### Expected Behavior

Sell order should give an increase in equity when the quote moves down.

### Actual Behavior

Sell order gives a loss on a downward move and a profit on an upward move

### Steps to Reproduce

1. Open https://colab.research.google.com/github/kernc/backtesting.py/blob/master/doc/examples/Trading%20with%20Machine%20Learning.ipynb
2. Run
3. See the any plot

### Additional info

![изображение](https://user-images.githubusercontent.com/52975957/195870904-0f43a956-e695-4a88-b3f9-5b7ed7e4d7dd.png)

**Comment by leowhynot** [comment]
this happens even if you set the commision to zero

**Comment by kernc** [comment]
Since the triangles are pointing up, those are, in fact, _long_ trades being closed at a loss.

Make sure to be closing trades with [`self.position.close()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Position.close), [`trade.close()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Trade.close) or [`self.buy(size=relevant_short_trade.size)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.buy).
