### ISSUE TITLE
Multiple take profits with a the same order

### ISSUE THREAD

**Issue by ben-eastwest** [kernc/backtesting.py#890]
Hello, 
Before I start trying to explore ways to do this, I wanted to ask if backtesting.py can handle multiple profit targets on the same position?
so as a basic example of what I am trying to achieve

profit1 = ma + 20
profit2 = ma+40
stop = ma - 50

 if crossover(self.data.Close, self.ma):
         self.buy(size = 2, tp=profit1, profit2, stop=stop)

I have tried a few different ways:

if crossover(self.data.Close, self.ma):
         self.buy(size = 1, tp=profit1, sl=stop)
         self.buy(size=1, tp=profit2, sl = stop)

if crossover(self.data.Close, self.ma):
         self.buy(size = 1, tp=profit1, sl=stop)
         if crossover(self.data.Close, self.ma):
                  self.buy(size=1, tp=profit2, sl = stop)

and a few others, but I would like to know that the library can't do this before I waste a lot of time trying to achieve the impossible!

**Comment by kernc** [comment]
> self.buy(size = 1, tp=profit1, sl=stop)
> self.buy(size=1, tp=profit2, sl = stop)

This is reasonable if your desired position size is divisible by 2.

**Comment by ben-eastwest** [comment]
Yes, this works now. Thank you so very much!

**Comment by djwatt3** [comment]
Hello, I am joining this issue because my question is very similar.
How I can place a new buy order with multiple take profits and different size?
example
`
sizes = [0.50, 0.25, 0.25]
order = self.buy(sl=stopLoss)
order.setTP1(size=sizes[0], limit=tp1)
order.setTP2(size=sizes[1], limit=tp2)
order.setTP3(size=sizes[2], limit=tp3)
`

Thanks
